/*
  EDIT THIS FILE FIRST.
  Replace placeholder text, links and image URLs below. The layout will update
  automatically. Keep the quotation marks around each text value.
*/
window.SITE_CONTENT = {
  announcement:
    "UNIVERSITY RESEARCH PROJECT  |  SOCIAL MEDIA MARKETING  |  F&B SMALL BUSINESSES IN KLANG VALLEY",
  universityLogoText: "UNIKL",
  // Optional: add a real logo file to images/ and use "./images/your-logo.png".
  // Leave this empty to keep the clean UNIKL text mark.
  universityLogoImage: "./images/Logo-02-nobackground.png?v=20260601-fnb4",
  brandName: "DIGITAL GROWTH",
  brandSubline: "F&B BUSINESS RESEARCH",
  universityName: "UNIVERSITI KUALA LUMPUR",
  universityNote:
    "This academic research project is prepared under Universiti Kuala Lumpur. Replace this note with your institute, programme and course details.",
  universityImage: "./images/UniKL-1.jpg?v=20260601-fnb2",
  researchTitle: "THE INFLUENCE OF SOCIAL MEDIA MARKETING ON BUSINESS GROWTH STABILITY",
  researchSummary:
    "A focused study of how social media marketing shapes the long-term growth stability of food and beverage small businesses across Klang Valley.",
  heroImage:
    "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=2200&q=90",
  lecturer: {
    name: "LECTURER FULL NAME",
    department: "BUSINESS SCHOOL / FACULTY",
    email: "LECTURER EMAIL",
    bio: "This research is developed under the guidance of our lecturer. Replace this text with the lecturer's academic background, area of expertise and role in supporting the project.",
    image:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Cristiano%20Ronaldo%202018.jpg?width=800",
  },
  members: [
    { name: "FULL NAME 1", id: "STUDENT ID: ID000001", image: "https://yg-babymonster-official.jp/wp/wp-content/uploads/2026/05/CHOOM_ASA_WEB.webp" },
    { name: "FULL NAME 2", id: "STUDENT ID: ID000002", image: "https://yg-babymonster-official.jp/wp/wp-content/uploads/2026/05/CHOOM_RUKA_WEB.webp" },
    { name: "FULL NAME 3", id: "STUDENT ID: ID000003", image: "https://yg-babymonster-official.jp/wp/wp-content/uploads/2026/05/CHOOM_PHARITA_WEB.webp" },
    { name: "FULL NAME 4", id: "STUDENT ID: ID000004", image: "https://yg-babymonster-official.jp/wp/wp-content/uploads/2026/05/CHOOM_AHYEON_WEB.webp" },
    { name: "FULL NAME 5", id: "STUDENT ID: ID000005", image: "https://yg-babymonster-official.jp/wp/wp-content/uploads/2026/05/CHOOM_RORA_WEB.webp" },
    { name: "FULL NAME 6", id: "STUDENT ID: ID000006", image: "https://yg-babymonster-official.jp/wp/wp-content/uploads/2026/05/CHOOM_CHIQUITA_WEB.webp" },
  ],
  about:
    "Social media has become an essential growth channel for independent cafés, restaurants, bakeries and beverage brands. This research explores whether consistent social media marketing can help small F&B businesses in Klang Valley achieve more stable business growth, build stronger customer relationships and remain competitive in a fast-moving digital marketplace.",
  aboutImage:
    "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1400&q=90",
  aboutPoints: [
    { title: "FOCUS", text: "F&B small businesses operating across Klang Valley." },
    { title: "CHANNEL", text: "Social media marketing as a driver of visibility and engagement." },
    { title: "OUTCOME", text: "Practical insight into sustainable business growth stability." },
  ],
  journey: [
    "Literature Review: Theory of Planned Behaviour",
    "Variables Identification & Research Framework",
    "Methodology & Google Form Questionnaire Link",
    "Autogenerated Results: Raw Data & Google Form Charts",
    "Respondent Demographic Profiles: SPSS Frequency Analysis",
    "Cross-Tabulations Analysis: SPSS Descriptive Data",
    "SmartPLS Model Generation & Data Interpretation: Likert-Scale Analysis",
    "Discussion of Journal Findings: Journals 1-5",
    "Conclusion & Recommendations",
    "References / Bibliography",
  ],
  researchSections: [
    {
      title: "Literature Review",
      subtitle: "Theory of Planned Behaviour",
      text: "",
      visual: "ADD THEORY OF PLANNED BEHAVIOUR DIAGRAM",
      media: "",
    },
    {
      title: "Variables Identification & Research Framework",
      subtitle: "Connecting digital activity to growth stability",
      text: "",
      visual: "ADD FINAL RESEARCH FRAMEWORK DIAGRAM",
      media: "",
    },
    {
      title: "Methodology",
      subtitle: "Research design and Google Form questionnaire",
      text: "",
      visual: "ADD RESEARCH PROCESS OR SAMPLING FLOW",
      media: "",
    },
    {
      title: "Autogenerated Results",
      subtitle: "Raw data and Google Form charts",
      text: "",
      visual: "ADD RAW DATA TABLE OR GOOGLE FORM CHARTS",
      media: "",
    },
    {
      title: "Respondent Demographic Profiles",
      subtitle: "SPSS frequency analysis",
      text: "",
      visual: "ADD SPSS FREQUENCY TABLES OR CHARTS",
      media: "",
    },
    {
      title: "Cross-Tabulations Analysis",
      subtitle: "SPSS descriptive data",
      text: "",
      visual: "ADD SPSS CROSS-TABULATION TABLES",
      media: "",
    },
    {
      title: "SmartPLS Model Generation & Data Interpretation",
      subtitle: "Likert-scale analysis",
      text: "",
      visual: "ADD SMARTPLS MODEL OR RESULTS",
      media: "",
    },
    {
      title: "Discussion of Journal Findings",
      subtitle: "Journals 1-5",
      text: "",
      visual: "ADD JOURNAL SUMMARY TABLE",
      media: "",
    },
    {
      title: "Conclusion & Recommendations",
      subtitle: "Final findings and proposed actions",
      text: "",
      visual: "ADD FINAL RECOMMENDATIONS OR ACTION PLAN",
      media: "",
    },
  ],
  questionnaire:
    "Are you an owner or operator of an F&B small business in Klang Valley? Your response will help us understand how social media marketing influences business growth stability. Replace the sample link with your final Google Form questionnaire.",
  questionnaireUrl: "https://forms.google.com/",
  questionnaireImage:
    "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=90",
  references:
    "Add your complete APA-formatted references here. Include the Theory of Planned Behaviour source, five selected journal articles and supporting sources related to social media marketing, small businesses, the F&B sector and business growth stability.",
  contact: "PROJECT EMAIL\nBUSINESS SCHOOL / FACULTY\nUNIVERSITI KUALA LUMPUR",
  footerNote:
    "An academic research website examining social media marketing and stable growth among Klang Valley F&B small businesses.",
  year: "2026",
};
